# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  crud-best-practice-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    # volumes:
    #   - ~/volumes/jhipster/crud-best-practice/elasticsearch/:/usr/share/elasticsearch/data/
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      - 'xpack.security.enabled=false'
      - 'discovery.type=single-node'
      - 'bootstrap.memory_lock=true'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

  crud-best-practice-kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    container_name: crud-best-practice
    environment:
      SERVER_NAME: kibana-server
      ELASTICSEARCH_URL: 127.0.0.1:9200:9200
    ports:
      - "5601:5601"
